CREATE SCHEMA IF NOT EXISTS `proyectop312023` DEFAULT CHARACTER SET utf8 ;
USE `proyectop312023`;

CREATE TABLE IF NOT EXISTS tbl_usuario (
	usuid INT NOT NULL AUTO_INCREMENT,
	usunombre VARCHAR(45) NOT NULL,
	usucontrasena VARCHAR(25) NOT NULL,
	PRIMARY KEY (usuid) )
ENGINE = InnoDB CHARACTER SET = latin1;

CREATE TABLE IF NOT EXISTS tbl_app (
	appid INT NOT NULL AUTO_INCREMENT,
	appnombre VARCHAR(45) NOT NULL,
	appestado VARCHAR(1) NOT NULL,
	PRIMARY KEY (appid) )
ENGINE = InnoDB CHARACTER SET = latin1;